final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Men\'s Nike Shoes',
    'price': 60.00,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '5',
    'title': 'Addidas Shoes',
    'price': 33.33,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '6',
    'title': 'Bata Shoes',
    'price': 30.21,
    'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '7',
    'title': 'Jordan Shoes',
    'price': 550.00,
    'imageUrl': 'assets/images/shoes_8.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
];
